# Generated by Django 4.2.4 on 2023-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='current_score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='lastgame',
            field=models.DateField(null=True),
        ),
    ]
