# Generated by Django 4.2.4 on 2023-08-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0004_alter_gamedata_lastgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
